switch argument0
{
    case 0:
        Notavalmessage = "Unavailable"
        optionname[0] = "Back"
        optionname[1] = "Language"
        optionname[2] = "Cheats"
        optionname[3] = "Font"
        optionname[4] = "FF progressbar"
        optionname[5] = "Show FPS"
        optionname[6] = "New content"
        optionname[7] = "White Noise Style"
        optionname[8] = "4:3 mode"
        optionname[9] = "Voiceover"
        optionname[10] = "Enable DCRP"
        optionname[11] = "Billineal filtering"
        optionname[12] = "Performance mode"
        optiondesc[0] = ""
        optiondesc[1] = "Pick your language"
        optiondesc[2] = "Enable debug mode and some cheats accecible with the numpad (enable numlock on your keyboard)"
        optiondesc[3] = "Pick between original NB font (korinna) and new NU font (pallete)"
        optiondesc[4] = "Toggle the progressbar in Fatal Fog"
        optiondesc[5] = "Show FPS"
        optiondesc[6] = "Toggle new content on or off"
        optiondesc[7] = "Change how overlayed noise works in subconcious mind"
        optiondesc[8] = "Change the screen resolution back to 4:3#VERY EXPERIMENTAL"
        optiondesc[9] = "Choose the voiceover you want (you can add your own by naming a folder voice_ )"
        optiondesc[10] = "Shows to other people that you are playing NBE"
        optiondesc[11] = "blurs your fucking game so it looks like shit"
        optiondesc[12] = "Dogshit solution"
    break;
    case 1:
        Notavalmessage = "Недоступно"
        optionname[0] = "Назад"
        optionname[1] = "Язык"
        optionname[2] = "Читы"
        optionname[3] = "Шрифт"
        optionname[4] = "Шкала прогресса в FF"
        optionname[5] = "Показать FPS"
        optionname[6] = "Новый контент"
        optionname[7] = "Стиль Белого Шума"
        optionname[8] = "Режим 4:3"
        optionname[9] = "Озвучка"
        optionname[10] = "Включить DCRP"
        optionname[11] = "Мыло Блять"
        optionname[12] = "Не лагать"
        optiondesc[0] = ""
        optiondesc[1] = "Выберите свой язык"
        optiondesc[2] = "Включает дебаг мод и некоторые читы доступные на нумпаде (Включи намлок на клавиатуре)"
        optiondesc[3] = "Выберите оригинальный шрифт НБ (Korinna) или шрифт нового НЮ (Pallete)"
        optiondesc[4] = "Переключение шкалы прогресса в FF"
        optiondesc[5] = "Показать FPS"
        optiondesc[6] = "Включить или выключить новый контент"
        optiondesc[7] = "Изменить наложенный на экран белый шум в Fatal Fog"
        optiondesc[8] = "Вернуть разрешение экрана 4:3#ОЧЕНЬ ЭКСПЕРИМЕНТАЛЬНО"
        optiondesc[9] = "Choose the voiceover you want (you can add your own by naming a folder voice_ )"
        optiondesc[10] = "Shows to other people that you are playing NBE"
        optiondesc[11] = "blurs your fucking game so it looks like shit"
        optiondesc[12] = "Dogshit solution"
    break;
    case 2:
        Notavalmessage = "Unavailable"
        optionname[0] = "Back"
        optionname[1] = "Language"
        optionname[2] = "Cheats"
        optionname[3] = "Font"
        optionname[4] = "FF progressbar"
        optionname[5] = "Show FPS"
        optionname[6] = "New content"
        optionname[7] = "SM Noise"
        optionname[8] = "4:3 mode"
        optionname[9] = "Voiceover"
        optionname[10] = "Enable DCRP"
        optionname[11] = "Billineal filtering"
        optionname[12] = "Performance mode"
        optiondesc[0] = ""
        optiondesc[1] = "Pick your language"
        optiondesc[2] = "Enable debug mode and some cheats accecible with the numpad (enable numlock on your keyboard)"
        optiondesc[3] = "Pick between original NB font (korinna) and new NU font (pallete)"
        optiondesc[4] = "Toggle the progressbar in Fatal Fog"
        optiondesc[5] = "Show FPS"
        optiondesc[6] = "Toggle new content on or off"
        optiondesc[7] = "Change how overlayed noise works in subconcious mind"
        optiondesc[8] = "Change the screen resolution back to 4:3#VERY EXPERIMENTAL"
        optiondesc[9] = "Choose the voiceover you want (you can add your own by naming a folder voice_ )"
        optiondesc[10] = "Shows to other people that you are playing NBE"
        optiondesc[11] = "blurs your fucking game so it looks like shit"
        optiondesc[12] = "Dogshit solution"
    break;
}
